{% set name = "pynmea2" %}
{% set version = "1.18.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynmea2-{{ version }}.tar.gz
  sha256: e340d3327ebf09683d09466a52541dfcccb98bde9cb661cab2d3eeb72ea424ad

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - pynmea2
    - pynmea2.types
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Knio/pynmea2
  summary: Python library for the NMEA 0183 protcol
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
