{% set version = "1.16.0" %}

package:
  name: pynmea2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pynmea2/pynmea2-{{ version }}.tar.gz
  sha256: 4fbb2a293883b24932e8403730f654b479828c218b00470031478c53202e2f71

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pynmea2
    - pynmea2.types
    - pynmea2.types.proprietary

about:
  home: https://github.com/Knio/pynmea2
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python library for the NMEA 0183 protcol

extra:
  recipe-maintainers:
    - ocefpaf
